cafe/urls.py
from django.urls import path

from .views import (
    index,
    contacts,
    DishTypeListView,
    DishTypeDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookExperienceUpdateView,
    CookDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("contacts/", contacts, name="contacts"),
    path(
        "menu/",
        DishTypeListView.as_view(),
        name="menu-list",
    ),
    path(
        "menu/<int:pk>/",
        DishTypeDetailView.as_view(),
        name="menu-detail",
    ),
    path(
        "menu/create/",
        DishTypeCreateView.as_view(),
        name="menu-create",
    ),
    path(
        "menu/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="menu-update",
    ),
    path(
        "menu/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="menu-delete",
    ),
    path(
        "menu/dish/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail",
    ),
    path(
        "menu/dish/create/",
        DishCreateView.as_view(),
        name="dish-create",
    ),
    path(
        "menu/dish/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update",
    ),
    path(
        "menu/dish/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete",
    ),
    path(
        "chefs/",
        CookListView.as_view(),
        name="chef-list",
    ),
    path(
        "chefs/<int:pk>/",
        CookDetailView.as_view(),
        name="chef-detail",
    ),
    path(
        "chefs/create/",
        CookCreateView.as_view(),
        name="chef-create",
    ),
    path(
        "chefs/<int:pk>/update/",
        CookExperienceUpdateView.as_view(),
        name="chef-update",
    ),
    path(
        "chefs/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="chef-delete",
    ),
]

app_name = "cafe"

cafe_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("cafe.urls", namespace="cafe")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cafe/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from cafe_service import settings


class DishType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    dish_type = models.ForeignKey(
        DishType,
        on_delete=models.CASCADE
    )
    ingredients = models.ManyToManyField(
        Ingredient,
        related_name="dishes"
    )
    cooks = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="dishes"
    )

    class Meta:
        verbose_name_plural = "dishes"

    def __str__(self):
        return f"{self.name} ({self.dish_type}, ${self.price})"


class Cook(AbstractUser):
    MIN_YEARS_OF_EXPERIENCE = 0
    MAX_YEARS_OF_EXPERIENCE = 80

    years_of_experience = models.IntegerField(
        default=0,
        validators=[
            MinValueValidator(MIN_YEARS_OF_EXPERIENCE),
            MaxValueValidator(MAX_YEARS_OF_EXPERIENCE),
        ]
    )

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

cafe/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from cafe.models import Dish, DishType, Ingredient, Cook


class DishForm(forms.ModelForm):
    dish_type = forms.ModelChoiceField(
        queryset=DishType.objects.all(),
        widget=forms.RadioSelect,
    )
    ingredients = forms.ModelMultipleChoiceField(
        queryset=Ingredient.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )


class CookExperienceUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ["years_of_experience"]

cafe/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import DishForm, CookCreationForm, CookExperienceUpdateForm
from .models import DishType, Dish, Cook


@login_required
def index(request):
    num_dishes = Dish.objects.count()
    num_cooks = Cook.objects.count()

    context = {
        "num_dishes": num_dishes,
        "num_cooks": num_cooks,
        "url_home": True
    }

    return render(request, "cafe/index.html", context=context)


@login_required
def contacts(request):
    context = {"url_contact": True}

    return render(request, "cafe/contacts.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    extra_context = {"url_menu": True}


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType
    extra_context = {"url_menu": True}


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    extra_context = {"url_menu": True}
    fields = "__all__"
    success_url = reverse_lazy("cafe:menu-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    extra_context = {"url_menu": True}
    fields = "__all__"
    success_url = reverse_lazy("cafe:menu-list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    extra_context = {"url_menu": True}
    success_url = reverse_lazy("cafe:menu-list")


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish
    extra_context = {"url_menu": True}


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    extra_context = {"url_menu": True}
    form_class = DishForm
    success_url = reverse_lazy("cafe:menu-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    extra_context = {"url_menu": True}
    form_class = DishForm
    success_url = reverse_lazy("cafe:menu-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    extra_context = {"url_menu": True}
    success_url = reverse_lazy("cafe:menu-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    extra_context = {"url_chefs": True}


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    extra_context = {"url_chefs": True}


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    extra_context = {"url_chefs": True}
    form_class = CookCreationForm
    success_url = reverse_lazy("cafe:chef-list")


class CookExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    extra_context = {"url_chefs": True}
    form_class = CookExperienceUpdateForm
    success_url = reverse_lazy("cafe:chef-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    extra_context = {"chefs": True}
    success_url = reverse_lazy("cafe:chef-list")

templates/base.html
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/WebPage">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ ASSETS_ROOT }}/img/apple-icon.png">
  <link rel="icon" id="favicon" type="image/x-icon" href="{{ ASSETS_ROOT }}/img/favicon.svg">
  <title>Crêpes & Co</title>
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <link href="{{ ASSETS_ROOT }}/css/nucleo-icons.css" rel="stylesheet" />
  <link href="{{ ASSETS_ROOT }}/css/nucleo-svg.css" rel="stylesheet" />
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <link id="pagestyle" href="{{ ASSETS_ROOT }}/css/material-kit.css?v=3.0.0" rel="stylesheet" />
</head>

<body style="background-image: url({{ ASSETS_ROOT }}/img/bg.png)">
  {% if request.user.is_authenticated %}
    {% include 'includes/navigation.html' %}
  {% endif %}
  
  {% block content %}{% endblock content %}  

  {% include 'includes/footer.html' %} 

  {% include 'includes/scripts.html' %} 

  {% block javascripts %}{% endblock javascripts %}
</body>
</html>

templates/cafe/contacts.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="page-header align-items-start" style="min-height: calc(100vh - 69px)" loading="lazy">
    <div class="container">
      <div class="d-flex justify-content-center align-items-center pt-4 pb-5">
        <img class="d-lg-block w-25" src="{{ ASSETS_ROOT }}/img/logo.svg" alt="logo">
      </div>
      <div class="card blur shadow-blur box-shadow-xl overflow-hidden">
        <div class="card card-plain">
          <div class="pt-3 px-4">
            <h1 class="font-weight-bolder text-center mb-3">
              Contacts
            </h1>
            <h6 class="text-center m-0">
              We'd love to hear from you!
            </h6>
            <h6 class="text-center m-0">
              Whether you have a question, feedback, or just want to chat about crepes, <br>feel free to reach out using one of the methods below:
            </h6>
          </div>

          <div class="card-body">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-lg-4 ms-auto me-auto p-lg-4 mt-lg-0 mt-4">
                  <div class="card">
                    <div class="card-header position-relative z-index-2">
                      <a class="d-block shadow-dark">
                        <img src="{{ ASSETS_ROOT }}/img/img3.jpg" alt="img-crepes" class="img-fluid border-radius-lg">
                      </a>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 ms-auto me-auto mt-lg-0 mt-4">
                  <div class="d-flex flex-column align-items-center">
                    <div class="d-flex justify-content-around mb-5 w-100">
                      <div class="text-dark">
                        <div class="fs-5 font-weight-bolder mb-2">Call us</div>
                        <div><a href="tel:+1 234 5555-55-55" class="text-dark">+1 234 5555-55-55</a></div>
                        <div><a href="tel:+1 234 5555-66-66" class="text-dark">+1 234 5555-66-66</a></div>
                      </div>
                      <div class="text-dark">
                        <div class="fs-5 font-weight-bolder mb-2">Email us</div>
                        <div><a href="mailto:crepes&co@example.com" class="text-dark">crepes&co@example.com</a></div>
                      </div>
                    </div>
                    <div class="d-flex justify-content-around mb-5 w-100">
                      <div class="text-dark">
                        <div class="fs-5 font-weight-bolder mb-2">Social Media</div>
                        <div class="d-flex justify-content-around">
                          <a href="#" class="text-dark"><i class="fab fa-facebook text-lg"></i></a>
                          <a href="#" class="text-dark"><i class="fab fa-twitter text-lg"></i></a>
                          <a href="#" class="text-dark"><i class="fab fa-instagram text-lg"></i></a>
                        </div>
                      </div>
                      <div class="text-dark">
                        <div class="fs-5 font-weight-bolder mb-2">Address</div>
                        <a href="https://goo.gl/maps/FXUdJAppi1eZJfac6" class="text-dark">
                          <div>400 first ave. suite 700</div>
                          <div>Minneapolis, MN 55401</div>
                        </a>
                      </div>
                    </div>
                    <h6>We look forward to connecting with you!</h6>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/cafe/cook_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="page-header align-items-start" style="min-height: calc(100vh - 69px)" loading="lazy">
    <div class="container" style="max-width: 1000px">
      <div class="d-flex justify-content-center align-items-center pt-4 pb-5">
        <img class="d-lg-block w-25" src="{{ ASSETS_ROOT }}/img/logo.svg" alt="logo">
      </div>
      <div class="card blur shadow-blur box-shadow-xl overflow-hidden">
        <div class="card card-plain">
          <div class="pt-3 px-4">
            <h3 class="font-weight-bolder text-center">
              Are you sure you would like to remove {{ cook }}?
            </h3>
          </div>

          <div class="card-body">
            <form action="" method="post">
              {% csrf_token %}
              <div class="d-flex justify-content-center align-items-center">
                <button class="btn btn-sm bg-gradient-danger mb-0 me-3" type="submit">
                  Yes, remove
                </button>
                <a href="{% url 'cafe:chef-list' %}" class="btn btn-sm btn-outline-danger mb-0" type="button">
                  Cancel
                </a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/cafe/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header align-items-start" style="min-height: calc(100vh - 69px)" loading="lazy">
    <div class="container" style="max-width: 1000px">
      <div class="d-flex justify-content-center align-items-center pt-4 pb-5">
        <img class="d-lg-block w-25" src="{{ ASSETS_ROOT }}/img/logo.svg" alt="logo">
      </div>
      <div class="card blur shadow-blur box-shadow-xl overflow-hidden">
        <div class="card card-plain">
          <div class="pt-3 px-4">
            <h2 class="font-weight-bolder text-center">
              About {{ cook }}
            </h2>
          </div>

          <div class="card-body px-5">
            <div class="mb-3 text-dark">
              <span class="fs-5 font-weight-bolder">Name: </span>
              {{ cook.first_name }} {{ cook.last_name }}
            </div>
            <div class="mb-3 text-dark">
              <span class="fs-5 font-weight-bolder">Username: </span>
              {{ cook.username }}
            </div>
            <div class="mb-3 text-dark">
              <span class="fs-5 font-weight-bolder">Years of experience: </span>
              {{ cook.years_of_experience }}
              <a class="text-dark" href="{% url 'cafe:chef-update' cook.id %}">
                <i class="material-icons mx-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Update">edit</i>
              </a>
            </div>
            <div class="mb-3 text-dark">
              <span class="fs-5 font-weight-bolder">Menu positions: </span>
              <ul class="list-group list-group-flush">
              {% for dish in cook.dishes.all %}
                <li class="list-group-item border-0 pb-0" style="background: none">
                  <a href="{% url 'cafe:dish-detail' dish.id %}" class="text-dark">
                    {{ dish }}
                  </a>
                </li>
                {% empty %}
                <li class="list-group-item border-0" style="background: none">
                  No dishes yet
                </li>
              {% endfor %}
              </ul>
            </div>

            <h6 class="text-center">
              The chef quit? Remove his!
            </h6>
            <div class="d-flex justify-content-center align-items-center">
              <a href="{% url 'cafe:chef-delete' cook.id %}" class="btn btn-sm bg-gradient-danger mb-0">Remove</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/cafe/cook_list.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header align-items-start" style="min-height: calc(100vh - 69px)" loading="lazy">
    <div class="container" style="max-width: 1000px">
      <div class="d-flex justify-content-center align-items-center pt-4 pb-5">
        <img class="d-lg-block w-25" src="{{ ASSETS_ROOT }}/img/logo.svg" alt="logo">
      </div>
      <div class="card blur shadow-blur box-shadow-xl overflow-hidden">
        <div class="card card-plain">
          <div class="pt-3 px-4">
            <h1 class="font-weight-bolder text-center mb-3">
              Chefs
            </h1>
            <h6 class="text-center m-0">
              Our chefs are culinary artists.  
            </h6>
            <h6 class="text-center m-0">
              From savory symphonies to sweet serenades, their creations are a delight for both palate and eye.
            </h6>
          </div>

          <div class="card-body">
            <ul class="list-group list-group-flush mb-5">
              {% for cook in cook_list %}
                <li class="list-group-item border-0" style="background: none">
                  <a href="{% url 'cafe:chef-detail' cook.id %}">
                    <div class="text-dark d-flex justify-content-center align-items-center">
                      <h5>{{ cook.first_name }} {{ cook.last_name }} ({{ cook.years_of_experience }} year{% if cook.years_of_experience > 1 %}s{% endif %} experience)</h5>
                    </div>
                  </a>
                </li>
              {% endfor %}
            </ul>

            <h6 class="text-center">
              New chef? Add his!
            </h6>
            <div class="d-flex justify-content-center align-items-center">
              <a href="{% url "cafe:chef-create" %}" class="btn btn-sm bg-gradient-danger mb-0">Add new chef</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/cafe/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header align-items-start" style="min-height: calc(100vh - 69px)" loading="lazy">
    <div class="container" style="max-width: 1000px">
      <div class="d-flex justify-content-center align-items-center pt-4 pb-5">
        <img class="d-lg-block w-25" src="{{ ASSETS_ROOT }}/img/logo.svg" alt="logo">
      </div>
      <div class="card blur shadow-blur box-shadow-xl overflow-hidden">
        <div class="card card-plain">
          <div class="pt-3 px-4">
            <h2 class="font-weight-bolder text-center">
              {{ dish.name }}
              <a class="text-dark" href="{% url 'cafe:dish-update' dish.id %}">
                <i class="material-icons mx-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Update">edit</i>
              </a>
            </h2>
          </div>

          <div class="card-body">
            <div class="mb-3 text-dark"><span class="fs-5 font-weight-bolder">Description: </span>{{ dish.description }}</div>
            <div class="mb-3 text-dark"><span class="fs-5 font-weight-bolder">Price: </span>${{ dish.price }}</div>
            <div class="mb-3 text-dark">
              <span class="fs-5 font-weight-bolder">Ingredients: </span>
              <ul class="list-group list-group-flush">
              {% for ingredient in dish.ingredients.all %}
                <li class="list-group-item border-0 pb-0" style="background: none">
                  {{ ingredient }}
                </li>
                {% empty %}
                <li class="list-group-item border-0" style="background: none">
                  No ingredients
                </li>
              {% endfor %}
              </ul>
            </div>
           <div class="mb-3 text-dark">
              <span class="fs-5 font-weight-bolder">Сhefs: </span>
              <ul class="list-group list-group-flush">
              {% for chef in dish.cooks.all %}
                <li class="list-group-item border-0 pb-0" style="background: none">
                  <a href="{% url 'cafe:chef-detail' chef.id %}" class="text-dark">
                    {{ chef }}
                  </a>
                </li>
                {% empty %}
                <li class="list-group-item border-0" style="background: none">
                  No chefs
                </li>
              {% endfor %}
              </ul>
            </div>
          
            <h6 class="text-center">
              Irrelevant position? Remove it!
            </h6>
            <div class="d-flex justify-content-center align-items-center">
              <a href="{% url 'cafe:dish-delete' dish.id %}" class="btn btn-sm bg-gradient-danger mb-0">Remove</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/cafe/dishtype_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header align-items-start" style="min-height: calc(100vh - 69px)" loading="lazy">
    <div class="container" style="max-width: 1000px">
      <div class="d-flex justify-content-center align-items-center pt-4 pb-5">
        <img class="d-lg-block w-25" src="{{ ASSETS_ROOT }}/img/logo.svg" alt="logo">
      </div>
      <div class="card blur shadow-blur box-shadow-xl overflow-hidden">
        <div class="card card-plain">
          <div class="pt-3 px-4">
            <h2 class="font-weight-bolder text-center">
              {{ dishtype.name }}
              <a class="text-dark" href="{% url 'cafe:menu-update' dishtype.id %}">
                <i class="material-icons mx-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Update name">edit</i>
              </a>
            </h2>
          </div>

          <div class="card-body">
            <ul class="list-group list-group-flush mb-5">
              {% for dish in dishtype.dish_set.all %}
                <li class="list-group-item border-0" style="background: none">
                  <a href="{% url 'cafe:dish-detail' dish.id %}">
                    <div class="text-dark d-flex justify-content-between">
                      <h6>{{ dish.name }}</h6>
                      <span>${{ dish.price }}</span>
                    </div>
                  </a>
                </li>
                {% empty %}
                  <div class="text-center">No position yet</div>
              {% endfor %}
            </ul>
          
            <h6 class="text-center">
              Irrelevant section? Remove it!
            </h6>
            <div class="d-flex justify-content-center align-items-center">
              <a href="{% url 'cafe:menu-delete' dishtype.id %}" class="btn btn-sm bg-gradient-danger mb-0">Remove</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/cafe/dishtype_list.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header align-items-start" style="min-height: calc(100vh - 69px)" loading="lazy">
    <div class="container" style="max-width: 1000px">
      <div class="d-flex justify-content-center align-items-center pt-4 pb-5">
        <img class="d-lg-block w-25" src="{{ ASSETS_ROOT }}/img/logo.svg" alt="logo">
      </div>
      <div class="card blur shadow-blur box-shadow-xl overflow-hidden">
        <div class="card card-plain">
          <div class="pt-3 px-4">
            <h1 class="font-weight-bolder text-center mb-3">
              Menu
            </h1>
            <h6 class="text-center m-0">
              Fresh ingredients. Endless possibilities. Discover your perfect crepe.
            </h6>
            <h6 class="text-center m-0">
              Start your day right with our delicious breakfast crepes. Or indulge in a sweet treat any time!
            </h6>
          </div>

          <div class="card-body">
            <ul class="list-group list-group-flush mb-5">
              {% for dishtype in dishtype_list %}
                <li class="list-group-item border-0" style="background: none">
                  <a href="{% url 'cafe:menu-detail' dishtype.id %}">
                    <div class="text-dark d-flex justify-content-center align-items-center">
                      <h4>{{ dishtype.name }}</h4>
                    </div>
                  </a>
                  <ul class="list-group list-group-flush">
                    {% for dish in dishtype.dish_set.all %}
                      <li class="list-group-item border-0" style="background: none">
                        <a href="{% url 'cafe:dish-detail' dish.id %}">
                          <div class="text-dark d-flex justify-content-between">
                            <h6>{{ dish.name }}</h6>
                            <span>${{ dish.price }}</span>
                          </div>
                        </a>
                      </li>
                      {% empty %}
                        <span class="text-center">No position yet</span>
                    {% endfor %}
                  </ul>
                </li>
              {% endfor %}
            </ul>

            <h6 class="text-center">
              Are there new menu items? Add them!
            </h6>
            <div class="d-flex justify-content-center align-items-center">
              <a href="{% url "cafe:menu-create" %}" class="btn btn-sm bg-gradient-danger mb-0 me-2">Add new section</a>
              <a href="{% url "cafe:dish-create" %}" class="btn btn-sm bg-gradient-danger mb-0 mx-2">Add new position</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/includes/footer.html
<footer class="footer mt-4">
  <div class="container">
    <div class="text-center">
      <p class="text-dark my-4 text-sm font-weight-normal">
        © 2024 Crêpes & Co. All rights reserved
      </p>
    </div>
  </div>
</footer>

templates/includes/navigation.html
<nav class="navbar navbar-expand-lg position-absolute top-0 z-index-3 w-100 shadow-none my-3">
  <div class="navbar-nav navbar-nav-hover w-100 justify-content-between flex-row">
    <div class="nav-item dropdown dropdown-hover mx-2">
      <a class="nav-link ps-2 cursor-pointer" id="dropdownMenuDocs" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="material-icons" style="font-size: 40px">menu</i>
      </a>
      <style>#dropdown-menu:before { display: none }</style>
      <div class="dropdown-menu dropdown-menu-animation dropdown-md dropdown-md-responsive mt-0 mt-lg-3 p-3 border-radius-lg" id="dropdown-menu" aria-labelledby="dropdownMenuDocs">
        <div class="d-none d-lg-block">
          <ul class="list-group">
            <li class="nav-item list-group-item border-0 p-0" style="height: 40px;">
              <a class="dropdown-item py-2 ps-3 border-radius-md d-flex justify-content-between align-items-center" href="{% url 'cafe:index' %}">
                <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Home</h6>
                {% if url_home %}
                  <img style="height: 24px;" src="{{ ASSETS_ROOT }}/img/favicon.svg" alt="logo">
                {% endif %}
              </a>
            </li>
            <li class="nav-item list-group-item border-0 p-0" style="height: 40px;">
              <a class="dropdown-item py-2 ps-3 border-radius-md d-flex justify-content-between align-items-center" href="{% url 'cafe:menu-list' %}">
                <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Menu</h6>
                {% if url_menu %}
                  <img style="height: 24px;" src="{{ ASSETS_ROOT }}/img/favicon.svg" alt="logo">
                {% endif %}
              </a>
            </li>
            <li class="nav-item list-group-item border-0 p-0" style="height: 40px;">
              <a class="dropdown-item py-2 ps-3 border-radius-md d-flex justify-content-between align-items-center" href="{% url 'cafe:chef-list' %}">
                <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Chefs</h6>
                {% if url_chefs %}
                  <img style="height: 24px;" src="{{ ASSETS_ROOT }}/img/favicon.svg" alt="logo">
                {% endif %}
              </a>
            </li>
            <li class="nav-item list-group-item border-0 p-0" style="height: 40px;">
              <a class="dropdown-item py-2 ps-3 border-radius-md d-flex justify-content-between align-items-center" href="{% url 'cafe:contacts' %}">
                <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Contacts</h6>
                {% if url_contact %}
                  <img style="height: 24px;" src="{{ ASSETS_ROOT }}/img/favicon.svg" alt="logo">
                {% endif %}
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="nav-item ms-lg-auto">
      <a class="nav-link nav-link-icon" href="{% url 'logout' %}">
        <i class="material-icons" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logout" style="font-size: 34px">logout</i>
      </a>
    </div>
  </div>
</nav>